"""Add email column to User model

Revision ID: 4126f1d0648c
Revises: 
Create Date: 2023-10-03 21:47:20.294156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4126f1d0648c'
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        
        
        



#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.drop_constraint(None, type_='unique')
#         batch_op.drop_column('email')

#     # ### end Alembic commands ###
def upgrade():
    # Drop the 'email' column from the 'user' table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

def downgrade():
    # This is optional, but if you want to add the 'email' column back in case you need it later, you can define it here
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))